### ISSUE TITLE
INL2 variance 

### ISSUE THREAD

**Issue by elisastefanini** [inertialsense/inertial-sense-ros#44]
Hi,
for my application I need the twist covariance in the /ins topic, so I I decomposed the function INS_variance_callback and all the other lines of code related to it in inertial_sense.cpp and inertial_sense.h but when I do catkin make to apply the new change, there are a lot of error about the code definition and variables like PvelNED and PxyzNED. Is there something that I can do to fix the problem?

**Comment by andrewpriddis** [comment]
I'm not sure if this will provide everything you need, but if you pull the development branch of inertial_sense_ros, we added covariance data to the standard ROS messages. Look over the docs/code for the development branch and if that has what you need. This new version of the ROS node will be compatible with our upcoming firmware release slated for early March 2022
